### ISSUE TITLE
property_evaluator_const.h

### ISSUE THREAD

**Issue by BeglViglosh** [KRodinn/OGSR-Engine#29]
Здравствуйте. Пытаюсь собрать ваш проект, но на стадии сборки xrGame компилятор начинает вываливаться на property_evaluator_const.h Соответственно, получить dll-ку не удается. Версия Visual Studio 15.6.4 Community Edition, SDK 10.0.16299.0. Ошибки такого рода:

> property_evaluator_const.h(19): error C4430: отсутствует спецификатор типа - предполагается int. 
> property_evaluator_const.h(22): error C2061: синтаксическая ошибка: идентификатор "_value_type" 
> property_evaluator_const.h(23): error C3646: evaluate: неизвестный спецификатор переопределения 
> property_evaluator_const.h(23): error C2059: синтаксическая ошибка: ) 
> property_evaluator_const.h(23): error C2238: непредвиденные лексемы перед ";" 

Что я делаю не так? Подскажите, пожалуйста.

**Comment by KRodinn** [comment]
В Readme ясно написано, что для сборки требуется Visual Studio 15.5.
Под студию 15.6 я ещё не адаптировал.

**Comment by ForserX** [comment]
Я у себя вроде правил.

**Comment by Xottab-DUTY** [comment]
@ForserX, подскажешь, что правил?)
