### ISSUE TITLE
Вылет при сохранении на x64

### ISSUE THREAD

**Issue by KRodinn** [KRodinn/OGSR-Engine#33]
Такое ощущение, что в нет-пакеты некоторых объектов записывается какой-то мусор / то ли сбивается позиция записи.
Самое интересное в этом, что если собирать с DEBUG дефайном (даже на релизной конфигурации, не вырубая оптимизацию и тп.), этого вылета нет. Такие чудеса.

**Comment by joye-ramone** [comment]
Еще вопрос, в чисто теоретически (если поправить скрипты) сохранки должны быть совместимы между 64 vs 86 ?

**Comment by KRodinn** [comment]
Конечно совместимы. Тот скрипт я [поправил](https://github.com/KRodinn/OGSE_0693_Optimized/commit/4112c0139070cbc70577a37de86e91fa0a23ee37), к стати.
