### ISSUE TITLE
[64] Question about vertex_in_direction and related script methods

### ISSUE THREAD

**Issue by joye-ramone** [KRodinn/OGSR-Engine#41]
Есть gamedata от мода новый арсенал 5. 
Скрипты адаптированные под ogsr. 
С 86 все работает на ура.

В 64 начинаются вылеты в скриптах xr_* методах
level.vertex_in_direction
level.vertex_position
и прочих, куда передается vertex если значение vertex 4294967295.
Но эти же методы не вылетают в 86 версии. И даже результаты выдают какие то. Не факт что правильные конечно.

Отсюда вопрос, действительно ли нельзя передавать 4294967295 в vertex или это что то не так с 64 сборкой? И если нельзя то почему не вылетает 86 сборка?

Тестовый скрипт:
            local r = level.vertex_in_direction(4294967295, vector():set(math.random(-1,1), 0, math.random(-1,1)), math.random(0,0.5))
            log1("vertex_in_direction result " .. r)
            local ver_pos = level.vertex_position(4294967295)
            log1("ver_pos == nil " .. tostring(ver_pos == nil))
            if ver_pos ~= nil then
                log1("ver_pos " .. ver_pos.x .. " " .. ver_pos.y .. " " .. ver_pos.z)
             end

**Comment by KRodinn** [comment]
xr_kamp.script? У меня щас на Янтаре такая же хрень. Разбираюсь.

**Comment by joye-ramone** [comment]
Да именно он, и именно на янтаре....

**Comment by joye-ramone** [comment]
Но в любом случае, значения вертекса 4294967295 это же не валидное?

**Comment by KRodinn** [comment]
Да. Вот и надо разобраться, почему там появляется невалидный вертекс. Такого не должно быть.

**Comment by KRodinn** [comment]
И к стати, хороший пример говнокода: math.random(0,0.5) - это прекрасно.

**Comment by joye-ramone** [comment]
это тестовый код :) будем улучшатся.

На всякий случай логи
64 https://pastebin.com/0PsbTPfQ
86 https://pastebin.com/6DEd3byY

**Comment by KRodinn** [comment]
Так он с оригинала кривой.

**Comment by dsh2dsh** [comment]
Сдается мне, что-то высчитывало вертекс, получило INVALID_STORY_ID и попыталось использовать это дальше. Что в таком случае должен делать движок - это вопрос. Мне кажется, вылетать - это нормально. И кстати, именно на Янтаре, я помню, что для одного из кампов зомбированных задан центр там, где нет валидного вертекса.

**Comment by KRodinn** [comment]
В огсе весь xr_kamp переделан. Но вылеты по невалидным вертексам есть в других местах. Эти вылеты - следствие, а надо в причинах разбираться, почему невалидный вертекс там появляется.
@dsh2dsh  не подскажешь, у какого именно кампа?

**Comment by dsh2dsh** [comment]
Во, нашел
https://github.com/dsh2dsh/op2ogse/commit/0af6658423dd9a58d02b2d95f8966895dd8ef953

**Comment by joye-ramone** [comment]
Денис, спасибо помогло для янтаря. Буду дальше ковырять.
Вылетать для невалидных  входных данных - это правильно, меня лишь смутило почему 86 сборка не вылетала.

**Comment by KRodinn** [comment]
Ага, на x86:
```
~~['xr_kamp'.CKampManager:getDestVertex ('yantar_zombies_kamp_4')] self.center = [4294967295]
~~['xr_kamp'.CKampManager:getDestVertex ('yantar_zombies_kamp_4')] level.vertex_in_direction returns = [4294967295]

```
А я уж было подумал, что это только на x64 начали невалидные вертексы появляться.
А они там всегда были, оказывается, просто вылета не было.
Вылет сейчас поправлю.

**Comment by joye-ramone** [comment]
Не, они точно есть и там и там. Только в одном случае вылетает, а в другом нет.

**Comment by KRodinn** [comment]
Ага, ну именно в случае с кампом зомби на янтаре, там просто в скрипте путь можно заменить на yantar_zombies_kamp_4_task, как и сделал @dsh2dsh .
А вот остальные вылеты из за вертекс_айди 4294967295 (а ведь такие ситуации довольно часто могут возникнуть) сходу поправить не удалось - там в куче мест слетает. Придётся там везде вертексы проверять на валидность, или придумывать более лучшее решение...
