### ISSUE TITLE
Вылетает на Steam версии

### ISSUE THREAD

**Issue by aka-sektor** [KRodinn/OGSR-Engine#49]
![default](https://user-images.githubusercontent.com/25452748/42135530-e19e7a26-7d54-11e8-83fe-863d5907acee.png)

Двиг ток поверх дисковой робит? Или он не предназначен для чистого ТЧ? Робит ток с модом OGSE 2.10R?

**Comment by KRodinn** [comment]
Хм, оригинально. Скинь полный лог.
Та версия, что в релизах, предназначена для чистого ТЧ.

**Comment by aka-sektor** [comment]
Лог не создается, только дамп в бинах

[xray_aka_sektor_07-01-18_18-03-55.zip](https://github.com/KRodinn/OGSR-Engine/files/2152870/xray_aka_sektor_07-01-18_18-03-55.zip)

**Comment by aka-sektor** [comment]
В стиме WorldWide, а не RU архивы. Поддерживает?

**Comment by KRodinn** [comment]
> В стиме WorldWide, а не RU архивы. Поддерживает?

Судя по тому, что у многих запускается, а у тебя нет - видимо, не поддерживает.
Добавил в TODO, в будущем может поправлю, как освобожусь.

**Comment by aka-sektor** [comment]
Если нет, то там по сути две буковки поменять в движке. RU на EN. Нет?
Вообще, хорошо бы двиг собирался мультиархивный.
Однако такое кажется даже в CoC не сделали.

**Comment by abramcumner** [comment]
Ерунда с разными архивами есть только в ТЧ. В ЧН и ЗП архивы одинаковые.

**Comment by aka-sektor** [comment]
Упс, ты прав, про CoC не в тему. Отличий по архивам нету.

**Comment by aka-sektor** [comment]
Проверил GOG-версию, русскую. Работает.
