### ISSUE TITLE
Какие версии Windows поддерживаются?

### ISSUE THREAD

**Issue by aka-sektor** [KRodinn/OGSR-Engine#50]
Не увидел этой информации.

Оригинал, шел на Windows: 2000 (SP4)/ XP (SP2)
Судя по требованиям на диске игры, да и в стиме.

Также, какие 3rd party требуются для работы?
Для оригинала вроде как:
Visual C++ 2005 x86 Redistributable
.NET Framework 3.0 
DirectX End-User Runtimes (June 2010)

**Comment by xrSimpAI** [comment]
Поддерживается **Windows 10 version 1803+**

> Также, какие 3rd party требуются для работы?

**Microsoft Visual C++ 2015-2024 Redistributable: https://aka.ms/vs/17/release/vc_redist.x64.exe**

**Comment by aka-sektor** [comment]
Угу, спасибо за инфу.
