### ISSUE TITLE
Почему указаны не все разработчики?

### ISSUE THREAD

**Issue by aka-sektor** [KRodinn/OGSR-Engine#51]
Разработчики почему-то только: KRodin, Dsh, KD

Но ведь сами указали "Перенесена большая часть правок оригинального OGSE и Xray Extensions, а так же из X-Ray Engine by Alpet & KD".

Разве не правильно ли было бы и всех остальных упомянуть?

**Comment by KRodinn** [comment]
[Тут](https://github.com/KRodinn/OGSR-Engine#%D0%91%D0%BB%D0%B0%D0%B3%D0%BE%D0%B4%D0%B0%D1%80%D0%B8%D0%BC) как бы указаны все основные проекты, файлы которых мы использовали, и люди, которым мы выражаем отдельную благодарность.
Если же я буду вообще всех-всех там указывать, там будет полотно на весь экран, если не больше.
Да это и не имеет смысла. Правки движков копипастятся из репо в репо постоянно, найти автора каждой правки невозможно по определению.
