### ISSUE TITLE
Нужны ли OGSR_Resources для сборки?

### ISSUE THREAD

**Issue by aka-sektor** [KRodinn/OGSR-Engine#52]
В инструкции по сборке указаны OGSR_Resources, необходимы ли они для сборки движка OGSR?

Если нет, то что это? Дальнейшее развитие последней версии OGSE?

**Comment by KRodinn** [comment]
Всё, что нужно для сборки - есть в этом репо. OGSR_Resources нужны для запуска собранного движка на OGSE 2.10R
А тебе для чего эта информация, собственно?
Ведь судя по твоим сообщениям, ты и близко не программист.
Ведь те, кто в этом хоть что-то понимают, таких вопросов бы не задавали.

**Comment by aka-sektor** [comment]
Возможность спросить есть, почему бы и нет.
Не думаю, что надо быть программистом чтобы собрать движок.
Нужно просто знать, что установить, что открыть, что нажать.

**Comment by KRodinn** [comment]
У меня просто бомбит от таких вопросов. И так ведь всё расписано максимально подробно.
Мне вот, никто ничего не разжёвывал, что установить, что открыть, что нажать.
Я всему сам научился.
Если только спрашивать, и просить ко всему пошаговую инструкцию - это к успеху не приведёт.
И да, я сегодня не в настроении.
