### ISSUE TITLE
Рабочий x64 по фичам

### ISSUE THREAD

**Issue by aka-sektor** [KRodinn/OGSR-Engine#53]
И ещё вопрос: что в случае с движком OGSR означает x64?

Поддержка многоядерных процессоров?
Более быстрая загрузка игры?
Движок "переваривает" большие по размеру уровни?

**Comment by KRodinn** [comment]
> Поддержка многоядерных процессоров?

Так она всегда была. И в оригинальном движке. Пусть даже кривая и глючная, но многоядерность была всегда.
В OGSR есть улучшения в этом плане, но это не зависит от x64

> Более быстрая загрузка игры?

Многопоточную загрузку текстур добавляли, какое-то ускорение она даёт, наверное. Но это, опять же, не зависит от x64.

> Движок "переваривает" большие по размеру уровни?

Да, мне сообщали об успешном запуске большой бесшовной локации.
Да и можно пихать в игру UHD текстуры, например.
x64 - это отсутствие ограничений по оперативной памяти для движка. И всё.
