### ISSUE TITLE
некоторые недочеты

### ISSUE THREAD

**Issue by JIuBeP** [KRodinn/OGSR-Engine#71]
Здравствуйте, заметил во время игры несколько недочетов или багов, некоторые с оригинала: 
-музыка в меню ближе к концу обрывается
-у заряженного обреза курок странно анимируется во время движения и остановки гг 
-в журнале пда прочитанные заметки остаются зелеными, по идее должны становится белыми
-иконки у защиты от электрошока и удара перепутаны местами
-полученные на пда интересные места отмеченные белым кружком, после загрузки сохранения пропадают
-у еды в инвентаре есть по правой кнопке мыши есть меню переместить в слот, но слота нет?
-альтернативный удар ножом на поверхностях и трупах не оставляет следов

Может еще перенести консоль из ЗП полупрозрачную с всплывающими командами? немного удобнее как по мне.
и добавить на кнопку x перенос всего из ящика, торговлю, по типу ЗП

**Comment by KRodinn** [comment]
Приветствую, Спасибо за багрепорт.

>-в журнале пда прочитанные заметки остаются зелеными, по идее должны становится белыми
>-иконки у защиты от электрошока и удара перепутаны местами

Поправим в ближайшее время.

>-полученные на пда интересные места отмеченные белым кружком, после загрузки сохранения пропадают

Это проблема кривых скриптов, мне кажется.

> -у еды в инвентаре есть по правой кнопке мыши есть меню переместить в слот, но слота нет?

Кривые конфиги. Поправлю.

> -у заряженного обреза курок странно анимируется во время движения и остановки гг

Посмотрю, что можно сделать. Если не потребуется правка модели - поправлю.

>-музыка в меню ближе к концу обрывается
>-альтернативный удар ножом на поверхностях и трупах не оставляет следов
>и добавить на кнопку x перенос всего из ящика, торговлю, по типу ЗП

Подумаем над этим.

>Может еще перенести консоль из ЗП полупрозрачную с всплывающими командами?

Не вижу смысла как-то, по крайней мере сейчас.

**Comment by dsh2dsh** [comment]
> и добавить на кнопку x перенос всего из ящика

Эта кнопка в конфиге назначается, в carbody.

**Comment by JIuBeP** [comment]
Хорошо, спасибо за ответы! 
Я еще вспомнил один небольшой недочет, возможно он тут уже исправлялся, в общем при попытке выстрелить из разряженного РПГ 7 появлялся на мгновение заряд и тут же исчезал.
 И можно сделать так чтобы поверхности прошивались с 2 сторон с отображением где прошла пуля, просто в ТЧ, даже при пробитии к примеру деревянного забора с обратной стороны не появлялось дырки, ну если так можно выразится. В ЧН и ЗП с этим хорошо было.

**Comment by joye-ramone** [comment]
РПГ 7проверю сегодня

**Comment by joye-ramone** [comment]
Я уже пытался это повторить. Но что то не получается...

**Comment by dsh2dsh** [comment]
Хм... Сейчас посмотрел свое последние видео - не видно заряда. Ладно, буду иметь ввиду, может замечу еще.

**Comment by JIuBeP** [comment]
Попробуйте заряженный РПГ7 разрядить, а затем выстрелить(лкм), должен мелькнуть, кстати в ЗП это похоже было исправлено.

**Comment by joye-ramone** [comment]
проверю именно такой случай тоже.
но мне кажется что это косяки ванильной модели и\или анимации.
у меня другие модели для РПГ и проблемы тоже нету

**Comment by joye-ramone** [comment]
Ага. при зарядке вижу. Но при пустом и выстреле не могу повторить

**Comment by joye-ramone** [comment]
А. кажется понял, @JIuBeP у тебя оружие само же заряжается когда пустой магазин?
Это наверно тот же баг про который пишет @dsh2dsh, просто у меня нету автозарядки оружия.
Все буду искать в коде проблему

**Comment by joye-ramone** [comment]
Проблема вот тут https://github.com/KRodinn/OGSR-Engine/blob/810f6804716253f9bc4da665cd1213aa89cd3964/ogsr_engine/xrGame/WeaponRPG7.cpp#L36

В самом начале анимации перезарядки кость с зарядом делается видимой (что бы было видно что мы ее заряжаем) и потом анимация ее уводит за экран. вот потому оно и мигает на долю секунды.
Не знаю что тут можно в движке сделать, это все таки наверно анимации...

**Comment by dsh2dsh** [comment]
Не понятно, зачем это делать перед запуском анимации зарядки. Логичнее было бы это делать по ее окончании.

**Comment by joye-ramone** [comment]
нет, так тоже не выйдет.
в самой анимации зарядки ГГ рукой вставляет заряд в ствол. если ее делать видимой в конце - будет вставлять пустоту.
нужно заводить анимацию idle_empty где граната будет уже за экраном и играть ее вместо idle когда нету заряда. по аналогии с пистолетами

**Comment by joye-ramone** [comment]
Нашел фикс из ЗП. скоро поправим

**Comment by JIuBeP** [comment]
Я просто по старой памяти писал) ну да точно, в оригинале же автоперезарядка после опустошения срабатывает, т.е. это происходило сразу же в момент начала перезарядки.  
А не исправлялись эти баги? 
-потеря типа зарядов в подствольнике при переводе оффлайн\онлайн
-исправлено обнуление типов зарядов в РГ-6 при переводе оффлайн\онлайн

**Comment by dsh2dsh** [comment]
Подствольник исправлялся. Про РГ6 не скажу, нужно пробовать.

**Comment by joye-ramone** [comment]
в RG6 как и в РПГ7 вроде бы это не должно быть проблемой. там же кол-во зарядов тоже что и у обычного оружия. Потом ничего не должно теряться.

**Comment by JIuBeP** [comment]
Ку. Еще несколько подозрительных моментов встретил, на всякий случай напишу:
-бинокль сталкеры воспринимают как оружие, не хотят разговаривать и просят убрать)
-сквозь закрытые дверцы шкафчиков можно подбирать предметы, т.е. не открывая их. 
-недавно найденные тайники на пда не мигают
-трупы редко могут стать невидимыми
-предметы из разбиваемых ящиков часто могут упасть сквозь потолок на пол

**Comment by JIuBeP** [comment]
Насчёт тайников извините, перепутал малясь с Чн, в ТЧ всегда были обычные метки.

**Comment by joye-ramone** [comment]
Вроде бы исправили все что к движку относилось.
